using System;
using System.Collections.Generic;
using Immersive.Framework.CycleReset;
using UnityEditor;
using UnityEngine;
namespace ImmersiveFrameworkQA.GameFlow.Internal.Editor.ImmersiveFrameworkQA.GameFlow.InternalEditor
{
    public static class QaH225ActivityCycleResetTriggerCompositionSmoke
    {
        private const string LogPrefix="[H225_ACTIVITY_CYCLE_RESET_TRIGGER_COMPOSITION_SMOKE]";
        private static bool ValidateRun()=>!EditorApplication.isPlaying;
        public static void Run(){var objects=new List<UnityEngine.Object>();var completed=new List<string>();try{GameObject empty=Root("H225 Empty",objects);var absent=ActivityCycleResetTriggerBinding.TryBind(new[]{empty,empty},new QaFakeActivityCycleResetRuntimePort());Require(absent.Succeeded&&absent.Status=="OptionalAbsent"&&absent.RootCount==1&&absent.TriggerCount==0,absent.Message);completed.Add("zero-triggers-optional");GameObject one=Root("H225 One",objects);var oneTrigger=one.AddComponent<ActivityCycleResetTrigger>();var port=new QaFakeActivityCycleResetRuntimePort();var bound=ActivityCycleResetTriggerBinding.TryBind(new[]{one,one},port);Require(bound.Succeeded&&bound.RootCount==1&&bound.TriggerCount==1&&bound.BoundCount==1&&oneTrigger.HasActivityCycleResetRuntimeBinding,bound.Message);completed.Add("one-trigger-bound");GameObject multiple=Root("H225 Multiple",objects);multiple.AddComponent<ActivityCycleResetTrigger>();var child=new GameObject("H225 Child");child.transform.SetParent(multiple.transform,false);objects.Add(child);child.AddComponent<ActivityCycleResetTrigger>();var all=ActivityCycleResetTriggerBinding.TryBind(new[]{multiple},new QaFakeActivityCycleResetRuntimePort());Require(all.Succeeded&&all.TriggerCount==2&&all.BoundCount==2,all.Message);completed.Add("multiple-triggers-all-bound");var same=ActivityCycleResetTriggerBinding.TryBind(new[]{one},port);Require(same.Succeeded&&same.IdempotentCount==1&&same.BoundCount==0,same.Message);completed.Add("same-port-idempotent");GameObject incompatible=Root("H225 Incompatible",objects);incompatible.AddComponent<ActivityCycleResetTrigger>();var badChild=new GameObject("H225 Incompatible Child");badChild.transform.SetParent(incompatible.transform,false);objects.Add(badChild);var bad=badChild.AddComponent<ActivityCycleResetTrigger>();bad.TryBindActivityCycleResetRuntime(new QaFakeActivityCycleResetRuntimePort(),out _);var rejected=ActivityCycleResetTriggerBinding.TryBind(new[]{incompatible},new QaFakeActivityCycleResetRuntimePort());Require(!rejected.Succeeded&&rejected.Status=="RejectedTriggerBinding"&&rejected.BoundCount==1&&rejected.RejectedCount==1,rejected.Message);completed.Add("incompatible-trigger-rejected");Debug.Log($"{LogPrefix} status='Passed' cases='{completed.Count}' completed='{string.Join(",",completed)}'.");}catch(Exception exception){Debug.LogError($"{LogPrefix} status='Failed' message='{exception.Message}'.");throw;}finally{foreach(UnityEngine.Object item in objects)if(item!=null)UnityEngine.Object.DestroyImmediate(item);}}
        private static GameObject Root(string name,ICollection<UnityEngine.Object> objects){var root=new GameObject(name);objects.Add(root);return root;}private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
    }
}
